name: learn-github-actions
run-name: ${{ github.actor }} is testing
on:
  push:
    branches:
      - main
jobs:
  go-lint-test:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      - name: Go lint
        run: npm run lint